FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD creational-patterns.jar /opt/creational-patterns/
EXPOSE 8080
WORKDIR /opt/creational-patterns/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "creational-patterns.jar"]
